# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'Storage'), (2, 'Store')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('id_building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SaCoeur.building')),
            ],
        ),
        migrations.CreateModel(
            name='product_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='id_product_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaCoeur.product_description'),
        ),
    ]
