# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SaCoeur', '0002_auto_20171215_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaCoeur.building'),
        ),
    ]
