# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SaCoeur', '0003_auto_20171215_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SaCoeur.Building'),
        ),
    ]
